# Generated by Django 4.2.7 on 2023-11-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, upload_to='static/images'),
        ),
    ]
