# Generated by Django 4.2.7 on 2023-11-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
